spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/articledb?serverTimezone=UTC
    username: root
    password: abc123
  redis:
    # host: 192.168.200.131
    sentinel:
      master: mymaster
      nodes: 192.168.200.131:26380,192.168.200.131:26381,192.168.200.131:26382
    database: 15
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

jwt:
  encodeStr: xiangzhouedu
  expireTime: 1800 #默认半小时
